apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: backend

resources:
  - ./k8s/secret.yaml
  - ./k8s/deployment.yaml
  - ./k8s/service.yaml
  - ./k8s/ingress.yaml
